/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface ICoffeeShop {
    function owner() external view returns (address);

    function isActive() external view returns (bool);

    function constructor() external;

    function addCoffee(uint64 cof_id, string calldata name, uint256 price) external;

    function getCoffee(uint256 id) external view returns (string memory, uint256);

    function buyCoffee(uint64 id) external payable;
}

